version: "3"

services:
  # nginx 컨테이너(서버)
  nginx:
    build: ./giftcard-nginx
    networks:
      - giftcard-net
    ports:
      - 80:8080
    volumes:
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      # - frontend

  db:
    container_name: giftcard_db_prod
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./settings/.env.db.prod
    networks:
      - giftcard-net
    ports:
      - "5432:5432"

  backend:
    container_name: giftcard_backend_prod
    build:
      context: ./giftcard-backend
      target: development
    env_file:
      - ./settings/.env.backend.prod
    command: yarn run start:debug
    networks:
      - giftcard-net
    ports:
      - "8000:8000"
      - "9229:9229"
    expose:
      - 8000
    volumes:
      - ./giftcard-backend/:/backend/
    depends_on:
      - db

  # frontend:
  #   container_name: giftcard_frontend_prod
  #   build:
  #     context: ./giftcard-frontend
  #   volumes:
  #     - ./giftcard-frontend/:/frontend
  #     - ./giftcard-frontend/node_modules/:/frontend/node_modules
  #     - build_folder:/frontend/build
  #   env_file:
  #     - ./settings/.env.frontend.prod
  #   environment:
  #     - CI=true
  #   tty: true
  #   command: ["yarn", "run", "build"]
  #   networks:
  #     - giftcard-net

  pgadmin:
    container_name: giftcard_pgadmin_prod
    image: dpage/pgadmin4
    env_file:
      - ./settings/.env.pgadmin.prod
    networks:
      - giftcard-net
    ports:
      - "5050:80"

networks:
  giftcard-net:
    driver: bridge

volumes:
  postgres_data:
  # build_folder:
